#!/usr/bin/env bash


if [ -n "$1" ]; then

	HOST=$1
	COUNT=0;
       
	while [ $COUNT = 0 ];
       		do
			host $HOST > /dev/null 2>&1;

			if [ $? = 0 ]; then
				echo "done" | mail -s "$HOST domain is ready" 5712515696@tmomail.net;
				COUNT=1;

				exit 0;
			fi;

		       	sleep 10;
       	done
else
	echo "write a hostname stupid"
fi

