#!/usr/bin/env bash
#Al Biheiri 20150501

note () {
	cat<<EOF

Example Usage: $0 USD ZAR

	AED  »  Arab Emirates Dirham
	AUD  »  Australian Dollar
	AZN  »  Azerbaijani Manat
	BHD  »  Bahraini Dinar
	BRL  »  Brazilian Real
	CAD  »  Canadian Dollar
	CHF  »  Swiss Franc
	CNY  »  Chinese Yuan Renminbi
	DKK  »  Danish Krone
	EGP  »  Egyptian Pound
	EUR  »  Euro
	GBP  »  British Pound Sterling
	HKD  »  Hong Kong Dollar
	INR  »  Indian Rupee
	JOD  »  Jordanian Dinar
	JPY  »  Japanese Yen
	KPW  »  North Korean Won
	KRW  »  South Korean Won
	KWD  »  Kuwaiti Dinar
	KYD  »  Caymanian Dollar 
	LVL  »  Latvian Lats
	MXN  »  Mexican Peso
	NZD  »  New Zealand Dollar
	OMR  »  Omani Rial
	NOK  »  Norwegian Krone
	PHP  »  Philippine Peso
	RUB  »  Russian Ruble
	SEK  »  Swedish Krona
	SGD  »  Singapore Dollar
	THB  »  Thailand Baht
	TRY  »  Turkish Lira
	USD  »  United States Dollar
	ZAR  »  South African Rand
EOF

}

if [[ $1 = "" ]]; then
	note; exit 1
fi

curl -s "http://rate-exchange.herokuapp.com/fetchRate?from=$1&to=$2" | awk -F \" '{print $12}'
