#!/bin/bash

HOST=$2
CHAIN="BLOCK"
SERVERS="jh vampire"

do_note () {
	cat <<EOF
	$0 [ls|r|a] [ipaddr | line number]
EOF
exit 1
}

if [[ $1 = "" ]]; then
	do_note
fi

do_add () {
	for i in $SERVERS;

		do 
		
		echo;
		echo $i;

			ssh $i "iptables -vnL $CHAIN | grep $HOST > /dev/null 2>&1"

			if [[ $? != 0 ]]; then
				ssh $i "iptables -A $CHAIN -s $HOST -j DROP; iptables -vnL $CHAIN --line; iptables-save > /etc/iptables"
			else
				echo "already exists in table: $HOST"
			fi;
			
		done
}

case $1 in
	"a"|"add")
		do_add
		;;
	"r"|"remove")
		for i in $SERVERS; do echo; echo $i; ssh $i "iptables -D $CHAIN $HOST; iptables -vnL $CHAIN --line; iptables-save > /etc/iptables"; done
		exit
		;;
	"ls"|"list")
		for i in $SERVERS; do echo; echo $i; ssh $i "iptables -vnL $CHAIN --line"; done
		exit
		;;
	*) do_note ;;
esac


