#!/bin/bash
#
# This script starts ssh-agent so you can ssh without typing in your
# passphrase for every ssh.  The needed environment variables for each
# shell are stored in ~/agents/<hostname>.  
#
# The needed env vars are: SSH-AGENT and SSH_AUTH_SOCK
#
# Also add this to your ~/.bashrc so all new shells get the env vars:
#
#   [ -e $HOME/agents/$HOSTNAME ] && . $HOME/agents/$HOSTNAME
#
# I also set up the "sb" alias to source .bashrc:
#
#   alias sb='. ~/.bashrc'
#
# $Id: keyme,v 1.3 2012/02/10 23:30:03 ryep Exp ryep $

echo ""

AGENT="$HOME/.ssh/agent/$HOSTNAME"
echo "agent file = $AGENT"

# Make sure the agents dir exists
[ -d $HOME/.ssh/agent ] || mkdir $HOME/.ssh/agent

# Clean up previous agents
killall -u $USER ssh-agent

eval `ssh-agent`
env | grep SSH_A > $AGENT
echo "export SSH_AGENT_PID" >> $AGENT
echo "export SSH_AUTH_SOCK" >> $AGENT
echo ""

ssh-add ~/.ssh/id_rsa
ssh-add ~/.ssh/id_rsa_github_jh
ssh-add ~/.ssh/dsa_ftnmail

echo ""
echo "  To kill the agent: ssh-agent -k"
echo ""
echo ""
