#!/bin/bash

EXTERNAL="/Volumes/SSD"

#rsync -va --delete "$HOME/Dropbox/" "$EXTERNAL/share/backups/abiheiri/Dropbox/"
#rsync -va --delete "$HOME/Dropbox/music production/" "$EXTERNAL/share/backups/audio-projects/music production/"

#iCloud to external

#sync Notes
rsync -va --delete "$HOME/Library/Mobile Documents/com~apple~TextEdit/Documents" "$EXTERNAL/share/backups/abiheiri/Notes/"

#sync music production
rsync -va --delete "$HOME/Library/Mobile Documents/com~apple~CloudDocs/music production/" "$EXTERNAL/share/backups/audio-projects/music production/"

#sync family docs and misc
rsync -va --delete --exclude 'music production' --exclude 'Documents' --exclude 'Downloads' "$HOME/Library/Mobile Documents/com~apple~CloudDocs/" "$EXTERNAL/share/backups/abiheiri/iCloud/"

#sync my documents folder
if [ $(hostname) = "Als-Macbook.local" ];
then
	rsync -va --delete "$HOME/Documents/" "$EXTERNAL/share/backups/abiheiri/twofah docs/"
fi

#sync pictures
#Dont delete remove data
rsync -va "$HOME/Pictures/AutoImport/" "$EXTERNAL/share/backups/backup-pics-videos/AutoImport/"
