#!/bin/bash

#OPTIONS='--stats --progress'
OPTIONS=''

#
# Sync to 2TB
#
if [[ -d "/Volume/SSD" ]]
then

	EXTERNAL_01="/Volumes/SSD"

	#####################
	# iCloud to external
	#####################

	#sync Notes
	rsync -va --delete "$HOME/Library/Mobile Documents/com~apple~TextEdit/Documents" "$EXTERNAL_01/share/backups/abiheiri/Notes/"

	#sync music production
	rsync -va --delete "$HOME/Library/Mobile Documents/com~apple~CloudDocs/music production/" "$EXTERNAL_01/share/backups/audio-projects/music production/"

	#sync family docs and misc
	rsync -va --delete --exclude 'music production' --exclude 'Documents' "$HOME/Library/Mobile Documents/com~apple~CloudDocs/" "$EXTERNAL_01/share/backups/abiheiri/iCloud/"

	#sync my documents folder
	if [ $(hostname) = "Als-Macbook.local" ];
	then
		rsync -va --delete "$HOME/Documents/" "$EXTERNAL_01/share/backups/abiheiri/twofah docs/"
	fi

	#sync pictures
	#Dont delete remove data
	rsync -va "$HOME/Pictures/AutoImport/" "$EXTERNAL_01/share/backups/backup-pics-videos/AutoImport/"

fi

#
# Sync to 64G
#
EXTERNAL_02="/Volumes/S64"

if [[ -d $EXTERNAL_02 ]]
then

    rsync -va $OPTIONS --delete "$HOME/Library/Mobile Documents/com~apple~CloudDocs/" "$EXTERNAL_02/iCloud/"

fi




