#!/bin/bash


#
# Sync to 2TB
#
if [[ -d "/Volume/SSD" ]]
then

	EXTERNAL="/Volumes/SSD"

	#####################
	# iCloud to external
	#####################

	#sync Notes
	rsync -va --delete "$HOME/Library/Mobile Documents/com~apple~TextEdit/Documents" "$EXTERNAL/share/backups/abiheiri/Notes/"

	#sync music production
	rsync -va --delete "$HOME/Library/Mobile Documents/com~apple~CloudDocs/music production/" "$EXTERNAL/share/backups/audio-projects/music production/"

	#sync family docs and misc
	rsync -va --delete --exclude 'music production' --exclude 'Documents' --exclude 'Downloads' "$HOME/Library/Mobile Documents/com~apple~CloudDocs/" "$EXTERNAL/share/backups/abiheiri/iCloud/"

	#sync my documents folder
	if [ $(hostname) = "Als-Macbook.local" ];
	then
		rsync -va --delete "$HOME/Documents/" "$EXTERNAL/share/backups/abiheiri/twofah docs/"
	fi

	#sync pictures
	#Dont delete remove data
	rsync -va "$HOME/Pictures/AutoImport/" "$EXTERNAL/share/backups/backup-pics-videos/AutoImport/"

fi

#
# Sync to 256G
#
if [[ -d "/Volumes/256" ]]
then

	EXTERNAL_256="/Volumes/256"

    rsync -va "$HOME/Library/Mobile Documents/com~apple~CloudDocs/" "$EXTERNAL_256/iCloud/"
    echo "This is not hostname -> Als-MacBook-Air.local ; I am not syncing icloud to the 256G"

fi




