#!/usr/bin/env bash
#
#this saves safari bookmarks and reading list


if [[ $(uname) != 'Darwin' ]]; then
	exit 99
fi

SAVE_LOCATION=~/Dropbox/docs-notes/bookmarks.txt

magic () {
	/usr/bin/plutil -convert xml1 -o - ~/Library/Safari/Bookmarks.plist | grep -E  -o '<string>http[s]{0,1}://.*</string>' | grep -v icloud | sed -E 's/<\/{0,1}string>//g'
}

case $1 in
	dry-run | dry | ls) magic ;;
	sync) 
		magic > $SAVE_LOCATION
		echo "Saved bookmarks to $SAVE_LOCATION"
		;;
	*) echo "append dry-run or sync at the end of the statement" ;;
esac

