#!/usr/bin/env bash
#
#this saves safari bookmarks and reading list


if [[ $(uname) != 'Darwin' ]]; then
	exit 1
fi

SAVE_LOCATION=(~/Dropbox/docs-notes/bookmarks.txt)

magic () {
	/usr/bin/plutil -convert xml1 -o - ~/Library/Safari/Bookmarks.plist | grep -E  -o '<string>http[s]{0,1}://.*</string>' | grep -v icloud | sed -E 's/<\/{0,1}string>//g'
}

usage () {
cat <<EOF
$0 [dry-run|sync|html]

This program exports safari web browser bookmarks and reading list.

dry-run|dry|ls:	lists all the bookmarks.
sync|save:	saves bookmarks to $SAVE_LOCATION. You can to edit the variable SAVE_LOCATION in the file $0. 
html:		converts list to html so you can save to a file and open it with your favorite web browser.

EOF
}

case $1 in
	dry-run | dry | ls)
		magic
		;;
	sync | save) 
		magic > $SAVE_LOCATION
		echo "Saved bookmarks to $SAVE_LOCATION"

		;;
	html)
		magic | sed 's/^https/http/' | sed 's/\(^http.*\)/\<a href ="\1"\>\1<\/a><br>/' | sort | uniq
		;;

	*) usage ;;
esac

